# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-27 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CutoutQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.CharField(help_text='Right Ascension. Format is as: 10.2345', max_length=30)),
                ('dec', models.CharField(help_text='Declination. Format is as: -0.2716', max_length=30)),
                ('radius', models.FloatField(help_text='Minimum value = 0.016666, maximum value = 5')),
                ('bands', models.CharField(choices=[('mwagleam_dr1_072-080', 'MWA GLEAM DR1 072-080'), ('mwagleam_dr1_072-103', 'MWA GLEAM DR1 072-103 (stacked)')], default=('mwagleam_dr1_072-080', 'MWA GLEAM DR1 072-080'), max_length=2)),
                ('plot_units', models.CharField(choices=[('fits', 'FITS'), ('jpeg', 'JPEG')], default=('fits', 'FITS'), max_length=2)),
            ],
        ),
    ]
