# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-24 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutout_extension', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoutquery',
            name='output_type',
            field=models.CharField(choices=[('fits', 'FITS'), ('png', 'PNG'), ('jpeg', 'JPEG')], default='fits', max_length=3),
        ),
    ]
