# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-21 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutout_extension', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoutquery',
            name='dec',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cutoutquery',
            name='ra',
            field=models.FloatField(),
        ),
    ]
