# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-27 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutout_extension', '0002_auto_20180927_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoutquery',
            name='plot_units',
            field=models.CharField(choices=[('fits', 'FITS'), ('jpeg', 'JPEG')], default=None, max_length=2),
        ),
    ]
