# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-21 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutout_extension', '0002_auto_20181021_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoutquery',
            name='ra',
            field=models.FloatField(max_length=2),
        ),
    ]
