# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-27 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutout_extension', '0004_auto_20180927_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoutquery',
            name='radius',
            field=models.IntegerField(help_text='Minimum value = 0.016666, maximum value = 5'),
        ),
    ]
