# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-27 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutout_extension', '0012_cutoutquery_bands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoutquery',
            name='dec',
            field=models.DecimalField(decimal_places=4, max_digits=30),
        ),
        migrations.AlterField(
            model_name='cutoutquery',
            name='ra',
            field=models.DecimalField(decimal_places=4, max_digits=30),
        ),
    ]
