# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-30 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutout_extension', '0014_auto_20180928_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutoutquery',
            name='bands',
            field=models.CharField(choices=[('072-080', 'MWA GLEAM DR1 072-080'), ('072-103', 'MWA GLEAM DR1 072-103 (stacked)'), ('072-080', 'MWA GLEAM DR1 072-080'), ('072-103', 'MWA GLEAM DR1 072-103 (stacked)'), ('080-088', 'MWA GLEAM DR1 080-088'), ('088-095', 'MWA GLEAM DR1 088-095'), ('095-103', 'MWA GLEAM DR1 095-103'), ('103-111', 'MWA GLEAM DR1 103-111'), ('103-134', 'MWA GLEAM DR1 103-134 (stacked)'), ('111-118', 'MWA GLEAM DR1 111-118'), ('118-126', 'MWA GLEAM DR1 118-126'), ('126-134', 'MWA GLEAM DR1 126-134'), ('139-147', 'MWA GLEAM DR1 139-147'), ('139-170', 'MWA GLEAM DR1 139-170 (stacked)'), ('147-154', 'MWA GLEAM DR1 147-154'), ('154-162', 'MWA GLEAM DR1 154-162'), ('162-170', ' MWA GLEAM DR1 162-170'), ('170-177', 'MWA GLEAM DR1 170-177'), ('170-231', 'MWA GLEAM DR1 170-231 (white)'), ('177-185', 'MWA GLEAM DR1 177-185'), ('185-193', 'MWA GLEAM DR1 185-193'), ('193-200', 'MWA GLEAM DR1 193-200'), ('200-208', 'MWA GLEAM DR1 200-208'), ('208-216', 'MWA GLEAM DR1 208-216'), ('216-223', 'MWA GLEAM DR1 216-223'), ('223-231', 'MWA GLEAM DR1 223-231')], default=None, max_length=26),
        ),
    ]
