# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-21 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutout_extension', '0015_auto_20180930_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cutoutquery',
            old_name='plot_units',
            new_name='output_units',
        ),
    ]
