# """
# Django settings for aao_cutout_api project.

# Generated by 'django-admin startproject' using Django 1.11.4.

# For more information on this file, see
# https://docs.djangoproject.com/en/1.11/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/1.11/ref/settings/
# """

# import os

# # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'apqga4h8g=n6x!oh-6976x4q%^+iadbqwj%p+$an0(j)8c2b^f'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = ['aao-api-test.ap-southeast-2.elasticbeanstalk.com',
#                  'localhost',
#                  '13.236.38.167',]


# # Application definition
# AWS_STORAGE_BUCKET_NAME = 'aao-api-test'
# AWS_S3_REGION_NAME = 'ap-southeast-2'  # e.g. us-east-2
# AWS_ACCESS_KEY_ID = 'AKIAIQ3UKXHYEWAF5Y7Q'
# AWS_SECRET_ACCESS_KEY = 'dNBbKMv7YpcoqFBGMQSjU4o98tKAJ9/B/ztkyIOM'

# # Tell django-storages the domain to use to refer to static files.
# AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

# # Tell the staticfiles app to use S3Boto3 storage when writing the collected static files (when
# # you run `collectstatic`).
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# AWS_S3_OBJECT_PARAMETERS = {
#     'Expires': 'Thu, 31 Dec 2099 20:00:00 GMT',
#     'CacheControl': 'max-age=94608000',
# }

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'rest_framework',
#     'cutout_extension.apps.CutoutExtensionConfig',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'aao_cutout_api.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': ['D:\\Code\\aaogroup17\\aao_cutout_api\\cutout_extension'],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'aao_cutout_api.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# # AWS DB
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME': 'aao',
# #         'USER': 'aao_db_user',
# #         'PASSWORD': 'CqhdnuXbtFhjRSXZz9WQ',
# #         'HOST': 'aaodbinstance.cytfdvqc5cvc.ap-southeast-2.rds.amazonaws.com',
# #         'PORT': '5432',
# #     }
# # }

# # Local sqlite3 DB
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# # if 'RDS_DB_NAME' in os.environ:
# #     DATABASES = {
# #         'default': {
# #             'ENGINE': 'django.db.backends.postgresql_psycopg2',
# #             'NAME': os.environ['RDS_DB_NAME'],
# #             'USER': os.environ['RDS_USERNAME'],
# #             'PASSWORD': os.environ['RDS_PASSWORD'],
# #             'HOST': os.environ['RDS_HOSTNAME'],
# #             'PORT': os.environ['RDS_PORT'],
# #         }
# #     }
# # else:
# #     # Local PostgreSQL DB
# #     DATABASES = {
# #         'default': {
# #             'ENGINE': 'django.db.backends.postgresql',
# #             'NAME': 'aao',
# #             'USER': 'postgres',
# #             'PASSWORD': 'postgres',
# #             'HOST': '127.0.0.1',
# #             'PORT': '5432',
# #         }
# #     }


# # Password validation
# # https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/1.11/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_L10N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/1.11/howto/static-files/

# # ENABLE WHEN LIVE HOSTING
# # STATICFILES_LOCATION = 'static'
# # STATICFILES_STORAGE = 'custom_storages.StaticStorage'

# # ENABLE WHEN LIVE HOSTING
# # MEDIAFILES_LOCATION = 'media'
# # DEFAULT_FILE_STORAGE = 'custom_storages.MediaStorage'

# STATIC_ROOT = os.path.join(BASE_DIR, "..", "www", "static")
# STATIC_URL = '/static/'

# #import os.path

# #PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))

# # STATICFILES_DIRS = (
# #     os.path.join(PROJECT_ROOT, 'static'),
# # )
